//! SQL schema generation from an approved event catalog (E3.2b).
//!
//! `generate_sql_schema` produces a deterministic SQL file with a `CREATE TABLE`
//! for the `infergen_events` table and a `CREATE VIEW` per approved event that
//! has at least one property, extracting each property from the JSON column.

use infergen_types::{CatalogEntry, EventProperty, EventStatus};

use crate::{Catalog, CATALOG_SCHEMA_VERSION};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// SQL dialect for schema generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SqlDialect {
    /// PostgreSQL — uses `JSONB`, `BIGSERIAL`, `TIMESTAMPTZ`.
    Postgres,
    /// MySQL / MariaDB — uses `JSON`, `BIGINT UNSIGNED AUTO_INCREMENT`, `DATETIME`.
    Mysql,
    /// SQLite — uses `TEXT` for properties, `INTEGER AUTOINCREMENT`.
    Sqlite,
}

impl SqlDialect {
    /// Lowercase string form of the dialect name.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            SqlDialect::Postgres => "postgres",
            SqlDialect::Mysql => "mysql",
            SqlDialect::Sqlite => "sqlite",
        }
    }
}

/// Generate a SQL schema string from an approved catalog.
///
/// Output includes:
/// 1. A `CREATE TABLE IF NOT EXISTS infergen_events` table.
/// 2. An index on `event_name`.
/// 3. A typed `CREATE VIEW` per approved event that has at least one property.
///
/// Only `Approved` entries are included. Output is deterministic.
#[must_use]
pub fn generate_sql_schema(catalog: &Catalog, dialect: SqlDialect) -> String {
    let mut events: Vec<&CatalogEntry> = catalog
        .events
        .iter()
        .filter(|e| e.status == EventStatus::Approved)
        .collect();
    events.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    write_schema_header(&mut out, dialect);
    write_events_table(&mut out, dialect);
    write_events_index(&mut out, dialect);

    let events_with_props: Vec<&&CatalogEntry> =
        events.iter().filter(|e| !e.properties.is_empty()).collect();

    if !events_with_props.is_empty() {
        out.push('\n');
        for entry in events_with_props {
            write_event_view(&mut out, entry, dialect);
        }
    }

    out
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

fn quote_identifier(name: &str, dialect: SqlDialect) -> String {
    match dialect {
        SqlDialect::Postgres | SqlDialect::Sqlite => format!("\"{name}\""),
        SqlDialect::Mysql => format!("`{name}`"),
    }
}

fn json_extract_expr(field: &str, dialect: SqlDialect) -> String {
    match dialect {
        SqlDialect::Postgres => format!("properties ->> '{field}'"),
        SqlDialect::Mysql => {
            format!("JSON_UNQUOTE(JSON_EXTRACT(properties, '$.{field}'))")
        }
        SqlDialect::Sqlite => format!("json_extract(properties, '$.{field}')"),
    }
}

fn write_schema_header(out: &mut String, dialect: SqlDialect) {
    out.push_str("-- Auto-generated by Infergen. Do not edit — run `infergen schema` to regenerate.\n");
    out.push_str(&format!(
        "-- infergen-core v{} · catalog schema v{} · dialect: {}\n",
        env!("CARGO_PKG_VERSION"),
        CATALOG_SCHEMA_VERSION,
        dialect.as_str(),
    ));
}

fn write_events_table(out: &mut String, dialect: SqlDialect) {
    out.push('\n');
    match dialect {
        SqlDialect::Postgres => {
            out.push_str("CREATE TABLE IF NOT EXISTS \"infergen_events\" (\n");
            out.push_str("  id BIGSERIAL PRIMARY KEY,\n");
            out.push_str("  event_name TEXT NOT NULL,\n");
            out.push_str("  properties JSONB NOT NULL DEFAULT '{}',\n");
            out.push_str("  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n");
            out.push_str(");\n");
        }
        SqlDialect::Mysql => {
            out.push_str("CREATE TABLE IF NOT EXISTS `infergen_events` (\n");
            out.push_str("  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,\n");
            out.push_str("  event_name VARCHAR(255) NOT NULL,\n");
            out.push_str("  properties JSON NOT NULL,\n");
            out.push_str("  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n");
            out.push_str("  INDEX infergen_events_event_name_idx (event_name)\n");
            out.push_str(");\n");
        }
        SqlDialect::Sqlite => {
            out.push_str("CREATE TABLE IF NOT EXISTS \"infergen_events\" (\n");
            out.push_str("  id INTEGER PRIMARY KEY AUTOINCREMENT,\n");
            out.push_str("  event_name TEXT NOT NULL,\n");
            out.push_str("  properties TEXT NOT NULL DEFAULT '{}',\n");
            out.push_str("  created_at TEXT NOT NULL DEFAULT (datetime('now'))\n");
            out.push_str(");\n");
        }
    }
}

fn write_events_index(out: &mut String, dialect: SqlDialect) {
    match dialect {
        // MySQL inlines the index inside CREATE TABLE.
        SqlDialect::Mysql => {}
        SqlDialect::Postgres => {
            out.push('\n');
            out.push_str(
                "CREATE INDEX IF NOT EXISTS infergen_events_event_name_idx\n  ON \"infergen_events\" (event_name);\n",
            );
        }
        SqlDialect::Sqlite => {
            out.push('\n');
            out.push_str(
                "CREATE INDEX IF NOT EXISTS infergen_events_event_name_idx\n  ON \"infergen_events\" (event_name);\n",
            );
        }
    }
}

fn write_event_view(out: &mut String, entry: &CatalogEntry, dialect: SqlDialect) {
    let tbl = quote_identifier("infergen_events", dialect);
    let view = quote_identifier(&entry.name, dialect);

    let mut sorted_props: Vec<&EventProperty> = entry.properties.iter().collect();
    sorted_props.sort_by(|a, b| a.name.cmp(&b.name));

    out.push_str(&format!("-- {}\n", entry.name));

    match dialect {
        SqlDialect::Postgres | SqlDialect::Mysql => {
            out.push_str(&format!("CREATE OR REPLACE VIEW {view} AS\n"));
        }
        SqlDialect::Sqlite => {
            out.push_str(&format!("CREATE VIEW IF NOT EXISTS {view} AS\n"));
        }
    }

    out.push_str("  SELECT\n    id,\n    created_at");

    for prop in &sorted_props {
        let extract = json_extract_expr(&prop.name, dialect);
        let pii_suffix = if prop.pii { " -- @pii" } else { "" };
        out.push_str(&format!(",\n    {extract} AS {}{pii_suffix}", prop.name));
    }

    out.push_str(&format!(
        "\n  FROM {tbl}\n  WHERE event_name = '{}';\n\n",
        entry.name
    ));
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use infergen_types::{
        CatalogEntry, CatalogEventKind, EventProvenance, EventProperty, EventStatus,
        CATALOG_SCHEMA_VERSION,
    };

    fn make_catalog(entries: Vec<CatalogEntry>) -> Catalog {
        Catalog { schema_version: CATALOG_SCHEMA_VERSION, events: entries }
    }

    fn make_entry(name: &str, status: EventStatus) -> CatalogEntry {
        CatalogEntry {
            id: format!("evt_{name}"),
            name: name.to_owned(),
            description: String::new(),
            status,
            confidence: 0.9,
            kind: CatalogEventKind::PageView,
            provenance: vec![EventProvenance {
                source_path: "src/index.tsx".into(),
                line: None,
                adapter: "nextjs".into(),
            }],
            properties: Vec::new(),
            providers: Vec::new(),
        }
    }

    fn make_prop(name: &str, t: Option<&str>, pii: bool) -> EventProperty {
        EventProperty { name: name.into(), prop_type: t.map(Into::into), required: false, pii }
    }

    #[test]
    fn schema_postgres_has_create_table_infergen_events() {
        let sql = generate_sql_schema(&Catalog::default(), SqlDialect::Postgres);
        assert!(
            sql.contains(r#"CREATE TABLE IF NOT EXISTS "infergen_events""#),
            "output:\n{sql}"
        );
    }

    #[test]
    fn schema_mysql_has_create_table_backtick_quoted() {
        let sql = generate_sql_schema(&Catalog::default(), SqlDialect::Mysql);
        assert!(
            sql.contains("CREATE TABLE IF NOT EXISTS `infergen_events`"),
            "output:\n{sql}"
        );
    }

    #[test]
    fn schema_sqlite_has_create_table_double_quoted() {
        let sql = generate_sql_schema(&Catalog::default(), SqlDialect::Sqlite);
        assert!(
            sql.contains(r#"CREATE TABLE IF NOT EXISTS "infergen_events""#),
            "output:\n{sql}"
        );
        assert!(sql.contains("AUTOINCREMENT"), "output:\n{sql}");
    }

    #[test]
    fn schema_postgres_has_jsonb_column() {
        let sql = generate_sql_schema(&Catalog::default(), SqlDialect::Postgres);
        assert!(sql.contains("JSONB"), "output:\n{sql}");
    }

    #[test]
    fn schema_mysql_has_json_column() {
        let sql = generate_sql_schema(&Catalog::default(), SqlDialect::Mysql);
        assert!(sql.contains("JSON"), "output:\n{sql}");
        assert!(!sql.contains("JSONB"), "MySQL should not use JSONB\noutput:\n{sql}");
    }

    #[test]
    fn schema_sqlite_has_text_column_for_properties() {
        let sql = generate_sql_schema(&Catalog::default(), SqlDialect::Sqlite);
        assert!(sql.contains("properties TEXT"), "output:\n{sql}");
        assert!(!sql.contains("JSONB"), "SQLite should not use JSONB\noutput:\n{sql}");
    }

    #[test]
    fn schema_empty_catalog_has_no_views() {
        let sql = generate_sql_schema(&Catalog::default(), SqlDialect::Postgres);
        assert!(!sql.contains("CREATE VIEW"), "unexpected view\noutput:\n{sql}");
        assert!(!sql.contains("CREATE OR REPLACE VIEW"), "unexpected view\noutput:\n{sql}");
    }

    #[test]
    fn schema_single_event_no_props_no_view() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let sql = generate_sql_schema(&cat, SqlDialect::Postgres);
        assert!(!sql.contains("CREATE OR REPLACE VIEW"), "no-props event should not have view\noutput:\n{sql}");
    }

    #[test]
    fn schema_single_event_with_props_has_view_postgres() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.properties.push(make_prop("route", Some("string"), false));
        let cat = make_catalog(vec![entry]);
        let sql = generate_sql_schema(&cat, SqlDialect::Postgres);
        assert!(
            sql.contains(r#"CREATE OR REPLACE VIEW "page_viewed""#),
            "view missing\noutput:\n{sql}"
        );
        assert!(sql.contains("properties ->> 'route'"), "json extract missing\noutput:\n{sql}");
    }

    #[test]
    fn schema_event_view_includes_pii_comment() {
        let mut entry = make_entry("user_signed_in", EventStatus::Approved);
        entry.properties.push(make_prop("email", Some("string"), true));
        let cat = make_catalog(vec![entry]);
        let sql = generate_sql_schema(&cat, SqlDialect::Postgres);
        assert!(sql.contains("-- @pii"), "PII comment missing\noutput:\n{sql}");
    }

    #[test]
    fn schema_mysql_view_uses_json_unquote_extract() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.properties.push(make_prop("route", Some("string"), false));
        let cat = make_catalog(vec![entry]);
        let sql = generate_sql_schema(&cat, SqlDialect::Mysql);
        assert!(sql.contains("JSON_UNQUOTE(JSON_EXTRACT"), "MySQL json extract missing\noutput:\n{sql}");
    }

    #[test]
    fn schema_sqlite_view_uses_json_extract_fn() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.properties.push(make_prop("route", Some("string"), false));
        let cat = make_catalog(vec![entry]);
        let sql = generate_sql_schema(&cat, SqlDialect::Sqlite);
        assert!(
            sql.contains("CREATE VIEW IF NOT EXISTS"),
            "SQLite view syntax missing\noutput:\n{sql}"
        );
        assert!(
            sql.contains("json_extract(properties, '$.route')"),
            "SQLite json_extract missing\noutput:\n{sql}"
        );
    }

    #[test]
    fn schema_events_alphabetically_sorted_in_views() {
        let mut z = make_entry("zebra_event", EventStatus::Approved);
        z.properties.push(make_prop("x", None, false));
        let mut a = make_entry("alpha_event", EventStatus::Approved);
        a.properties.push(make_prop("x", None, false));
        let cat = make_catalog(vec![z, a]);
        let sql = generate_sql_schema(&cat, SqlDialect::Postgres);
        let alpha_pos = sql.find("alpha_event").unwrap();
        let zebra_pos = sql.find("zebra_event").unwrap();
        assert!(alpha_pos < zebra_pos, "views not in alphabetical order\noutput:\n{sql}");
    }

    #[test]
    fn schema_ignored_event_no_view() {
        let mut entry = make_entry("noise_event", EventStatus::Ignored);
        entry.properties.push(make_prop("route", None, false));
        let cat = make_catalog(vec![entry]);
        let sql = generate_sql_schema(&cat, SqlDialect::Postgres);
        assert!(!sql.contains("noise_event"), "ignored event should not appear\noutput:\n{sql}");
    }

    #[test]
    fn schema_proposed_event_no_view() {
        let mut entry = make_entry("maybe_event", EventStatus::Proposed);
        entry.properties.push(make_prop("route", None, false));
        let cat = make_catalog(vec![entry]);
        let sql = generate_sql_schema(&cat, SqlDialect::Postgres);
        assert!(!sql.contains("maybe_event"), "proposed event should not appear\noutput:\n{sql}");
    }

    #[test]
    fn schema_header_contains_dialect_name() {
        for (dialect, marker) in [
            (SqlDialect::Postgres, "postgres"),
            (SqlDialect::Mysql, "mysql"),
            (SqlDialect::Sqlite, "sqlite"),
        ] {
            let sql = generate_sql_schema(&Catalog::default(), dialect);
            assert!(sql.contains(marker), "dialect marker '{marker}' missing\noutput:\n{sql}");
        }
    }

    #[test]
    fn schema_deterministic() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.properties.push(make_prop("route", Some("string"), false));
        let cat = make_catalog(vec![entry]);
        let sql1 = generate_sql_schema(&cat, SqlDialect::Postgres);
        let sql2 = generate_sql_schema(&cat, SqlDialect::Postgres);
        assert_eq!(sql1, sql2);
    }
}
