//! Go code generation from an approved event catalog (E5.2).
//!
//! `generate_go` produces a deterministic, idiomatic Go package: typed property
//! structs, track functions, event-name constants, a `Track` namespace var,
//! a `Provider` interface, and a runtime with consent, region, and redaction
//! hooks.  Output is deterministic (events + properties sorted alphabetically,
//! no timestamps) and safe to commit or `.gitignore`.

use infergen_types::{CatalogEntry, EventProperty, EventStatus};

use crate::{Catalog, CATALOG_SCHEMA_VERSION};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Configuration for Go code generation.
#[derive(Debug, Clone)]
pub struct GoCodegenConfig {
    /// Also emit `Proposed` events in addition to `Approved`.
    ///
    /// Default: `false`.
    pub include_proposed: bool,
    /// Go package name for the generated file.
    ///
    /// Default: `"infergen"`.
    pub package_name: String,
}

impl Default for GoCodegenConfig {
    fn default() -> Self {
        Self {
            include_proposed: false,
            package_name: "infergen".to_owned(),
        }
    }
}

/// Generate a Go package source string from an approved catalog.
///
/// Only `Approved` entries are included by default; `Ignored` entries are
/// always excluded.  Set `config.include_proposed = true` to also include
/// `Proposed` entries.
///
/// Output is deterministic: events sorted alphabetically, properties sorted
/// alphabetically within each struct.
///
/// # Examples
/// ```rust
/// use infergen_core::codegen::{GoCodegenConfig, generate_go};
/// use infergen_core::Catalog;
/// let go = generate_go(&Catalog::default(), &GoCodegenConfig::default());
/// assert!(go.contains("package infergen"));
/// ```
#[must_use]
pub fn generate_go(catalog: &Catalog, config: &GoCodegenConfig) -> String {
    let mut events: Vec<&CatalogEntry> = catalog
        .events
        .iter()
        .filter(|e| {
            e.status == EventStatus::Approved
                || (config.include_proposed && e.status == EventStatus::Proposed)
        })
        .collect();
    events.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    write_header(&mut out, config);
    write_imports(&mut out);
    write_provider_interface(&mut out);
    write_runtime_state(&mut out);
    write_consent_module(&mut out);
    write_configure_fn(&mut out);
    write_dispatch_fn(&mut out);
    write_event_name_constants(&mut out, &events);

    for entry in &events {
        write_event_section(&mut out, entry);
    }

    write_track_namespace(&mut out, &events);
    out
}

// ---------------------------------------------------------------------------
// Private helpers — name conversion
// ---------------------------------------------------------------------------

/// Convert any snake_case / camelCase identifier to PascalCase.
fn to_go_pascal_case(name: &str) -> String {
    crate::namer::split_identifier(name)
        .into_iter()
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

/// Map a catalog `prop_type` to a Go type string.
fn go_type(prop_type: Option<&str>) -> &'static str {
    match prop_type {
        Some("string") => "string",
        Some("number") => "float64",
        Some("boolean") => "bool",
        _ => "any",
    }
}

// ---------------------------------------------------------------------------
// Private helpers — output builders
// ---------------------------------------------------------------------------

fn write_header(out: &mut String, config: &GoCodegenConfig) {
    out.push_str("// Code generated by Infergen. Do not edit — run `infergen generate` to regenerate.\n");
    out.push_str(&format!(
        "// infergen-core v{} · catalog schema v{}\n",
        env!("CARGO_PKG_VERSION"),
        CATALOG_SCHEMA_VERSION,
    ));
    out.push('\n');
    out.push_str(&format!("package {}\n", config.package_name));
}

fn write_imports(out: &mut String) {
    out.push('\n');
    out.push_str("import (\n");
    out.push_str("\t\"encoding/json\"\n");
    out.push_str("\t\"sync\"\n");
    out.push_str(")\n");
}

fn write_provider_interface(out: &mut String) {
    out.push('\n');
    out.push_str("// Provider receives analytics events.\n");
    out.push_str("type Provider interface {\n");
    out.push_str("\t// ID returns a unique identifier for this provider, e.g. \"posthog\".\n");
    out.push_str("\tID() string\n");
    out.push_str("\t// Track sends a single analytics event.\n");
    out.push_str("\tTrack(eventName string, properties map[string]any)\n");
    out.push_str("\t// Flush flushes any buffered events (optional — may be a no-op).\n");
    out.push_str("\tFlush()\n");
    out.push_str("\t// Shutdown performs a graceful shutdown (optional — may be a no-op).\n");
    out.push_str("\tShutdown()\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("// Config holds the runtime configuration passed to ConfigureInfergen.\n");
    out.push_str("type Config struct {\n");
    out.push_str("\t// Providers are the analytics destinations that receive every Track call.\n");
    out.push_str("\tProviders []Provider\n");
    out.push_str("\t// Consent sets the initial consent state. Default: ConsentUnknown (permissive).\n");
    out.push_str("\tConsent ConsentState\n");
    out.push_str("\t// Region sets the initial region tag for provider routing (e.g. \"eu\", \"us\").\n");
    out.push_str("\tRegion string\n");
    out.push_str("\t// RedactFn is an optional per-property redaction hook.\n");
    out.push_str("\tRedactFn RedactFn\n");
    out.push_str("}\n");
}

fn write_runtime_state(out: &mut String) {
    out.push('\n');
    out.push_str("// _mu guards all runtime state.\n");
    out.push_str("var _mu sync.RWMutex\n");
    out.push('\n');
    out.push_str("var (\n");
    out.push_str("\t_providers     []Provider\n");
    out.push_str("\t_consentState  ConsentState\n");
    out.push_str("\t_region        string\n");
    out.push_str("\t_redactFn      RedactFn\n");
    out.push_str(")\n");
}

fn write_consent_module(out: &mut String) {
    out.push('\n');
    out.push_str("// ConsentState describes the user's analytics consent.\n");
    out.push_str("type ConsentState string\n");
    out.push('\n');
    out.push_str("const (\n");
    out.push_str("\t// ConsentUnknown is the default: events are sent until consent is explicitly denied.\n");
    out.push_str("\tConsentUnknown ConsentState = \"unknown\"\n");
    out.push_str("\t// ConsentGranted means the user has opted in.\n");
    out.push_str("\tConsentGranted ConsentState = \"granted\"\n");
    out.push_str("\t// ConsentDenied means the user has opted out; events are dropped.\n");
    out.push_str("\tConsentDenied ConsentState = \"denied\"\n");
    out.push_str(")\n");
    out.push('\n');
    out.push_str("// RedactFn is a hook called for every property before dispatch.\n");
    out.push_str("// Return the (possibly redacted) value for eventName.propName.\n");
    out.push_str("type RedactFn func(eventName, propName string, value any) any\n");
    out.push('\n');
    out.push_str("// SetConsent updates the consent state.\n");
    out.push_str("func SetConsent(state ConsentState) {\n");
    out.push_str("\t_mu.Lock()\n");
    out.push_str("\t_consentState = state\n");
    out.push_str("\t_mu.Unlock()\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("// OptIn grants analytics consent.\n");
    out.push_str("func OptIn() { SetConsent(ConsentGranted) }\n");
    out.push('\n');
    out.push_str("// OptOut denies analytics consent; subsequent events are dropped.\n");
    out.push_str("func OptOut() { SetConsent(ConsentDenied) }\n");
    out.push('\n');
    out.push_str("// SetRegion sets a region tag used for provider routing.\n");
    out.push_str("func SetRegion(region string) {\n");
    out.push_str("\t_mu.Lock()\n");
    out.push_str("\t_region = region\n");
    out.push_str("\t_mu.Unlock()\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("// SetRedactFn installs a per-property redaction hook.\n");
    out.push_str("func SetRedactFn(fn RedactFn) {\n");
    out.push_str("\t_mu.Lock()\n");
    out.push_str("\t_redactFn = fn\n");
    out.push_str("\t_mu.Unlock()\n");
    out.push_str("}\n");
}

fn write_configure_fn(out: &mut String) {
    out.push('\n');
    out.push_str("// ConfigureInfergen initialises the Infergen runtime.\n");
    out.push_str("// Call once before any Track calls, e.g. in main() or TestMain.\n");
    out.push_str("func ConfigureInfergen(cfg Config) {\n");
    out.push_str("\t_mu.Lock()\n");
    out.push_str("\t_providers = cfg.Providers\n");
    out.push_str("\t_mu.Unlock()\n");
    out.push_str("\tif cfg.Consent != \"\" {\n");
    out.push_str("\t\tSetConsent(cfg.Consent)\n");
    out.push_str("\t}\n");
    out.push_str("\tif cfg.Region != \"\" {\n");
    out.push_str("\t\tSetRegion(cfg.Region)\n");
    out.push_str("\t}\n");
    out.push_str("\tif cfg.RedactFn != nil {\n");
    out.push_str("\t\tSetRedactFn(cfg.RedactFn)\n");
    out.push_str("\t}\n");
    out.push_str("}\n");
}

fn write_dispatch_fn(out: &mut String) {
    out.push('\n');
    out.push_str("// _dispatch fans out a single event to all configured providers.\n");
    out.push_str("func _dispatch(name string, props map[string]any) {\n");
    out.push_str("\t_mu.RLock()\n");
    out.push_str("\tconsent := _consentState\n");
    out.push_str("\tredact := _redactFn\n");
    out.push_str("\tproviders := _providers\n");
    out.push_str("\t_mu.RUnlock()\n");
    out.push('\n');
    out.push_str("\tif consent == ConsentDenied {\n");
    out.push_str("\t\treturn\n");
    out.push_str("\t}\n");
    out.push_str("\tif redact != nil {\n");
    out.push_str("\t\tfor k, v := range props {\n");
    out.push_str("\t\t\tprops[k] = redact(name, k, v)\n");
    out.push_str("\t\t}\n");
    out.push_str("\t}\n");
    out.push_str("\tfor _, p := range providers {\n");
    out.push_str("\t\tp.Track(name, props)\n");
    out.push_str("\t}\n");
    out.push_str("}\n");
}

fn write_event_name_constants(out: &mut String, events: &[&CatalogEntry]) {
    out.push('\n');
    if events.is_empty() {
        out.push_str("// No events are currently approved in the catalog.\n");
        return;
    }
    out.push_str("// EventName constants enumerate all tracked event names.\n");
    out.push_str("const (\n");
    for entry in events {
        let pascal = to_go_pascal_case(&entry.name);
        out.push_str(&format!(
            "\tEventName{pascal} = \"{}\"\n",
            entry.name
        ));
    }
    out.push_str(")\n");
}

fn write_property_struct(out: &mut String, entry: &CatalogEntry) {
    let pascal = to_go_pascal_case(&entry.name);
    let mut sorted_props: Vec<&EventProperty> = entry.properties.iter().collect();
    sorted_props.sort_by(|a, b| a.name.cmp(&b.name));

    if !entry.description.is_empty() {
        out.push_str(&format!(
            "// {pascal}Properties holds properties for the {} event.\n",
            entry.name
        ));
        out.push_str(&format!("// {}\n", entry.description));
    } else {
        out.push_str(&format!(
            "// {pascal}Properties holds properties for the {} event.\n",
            entry.name
        ));
    }

    if sorted_props.is_empty() {
        // Use a type alias to map[string]any for prop-less events (mirrors TS Record<string,never>).
        out.push_str(&format!(
            "type {pascal}Properties = map[string]any\n"
        ));
    } else {
        out.push_str(&format!("type {pascal}Properties struct {{\n"));
        for prop in &sorted_props {
            let field_name = to_go_pascal_case(&prop.name);
            let go_t = go_type(prop.prop_type.as_deref());
            if prop.pii {
                out.push_str(&format!(
                    "\t{field_name} {go_t} `json:\"{}\"` // pii:\"true\"\n",
                    prop.name
                ));
            } else {
                out.push_str(&format!(
                    "\t{field_name} {go_t} `json:\"{}\"`\n",
                    prop.name
                ));
            }
        }
        out.push_str("}\n");
    }
}

fn write_track_function(out: &mut String, entry: &CatalogEntry) {
    let pascal = to_go_pascal_case(&entry.name);
    out.push('\n');
    if entry.description.is_empty() {
        out.push_str(&format!("// Track{pascal} sends the {} event.\n", entry.name));
    } else {
        out.push_str(&format!(
            "// Track{pascal} sends the {} event.\n//\n// {}\n",
            entry.name, entry.description
        ));
    }
    out.push_str(&format!(
        "func Track{pascal}(props {pascal}Properties) {{\n"
    ));
    out.push_str("\tb, _ := json.Marshal(props)\n");
    out.push_str("\tvar m map[string]any\n");
    out.push_str("\t_ = json.Unmarshal(b, &m)\n");
    out.push_str(&format!("\t_dispatch(EventName{pascal}, m)\n"));
    out.push_str("}\n");
}

fn write_event_section(out: &mut String, entry: &CatalogEntry) {
    let pascal = to_go_pascal_case(&entry.name);
    out.push('\n');
    let prefix = format!("// ─── {} ", entry.name);
    let bar_len = 80usize.saturating_sub(prefix.len());
    let bar = "─".repeat(bar_len.max(2));
    out.push_str(&format!("{}{}\n", prefix, bar));
    out.push('\n');
    write_property_struct(out, entry);
    write_track_function(out, entry);
    let _ = pascal;
}

fn write_track_namespace(out: &mut String, events: &[&CatalogEntry]) {
    out.push('\n');
    if events.is_empty() {
        out.push_str("// Track is the namespace for all tracked events.\n");
        out.push_str("// No events are currently approved in the catalog.\n");
        out.push_str("var Track = struct{}{}\n");
        return;
    }

    out.push_str("// Track is the namespace for all tracked events.\n");
    out.push_str("//\n");
    out.push_str("// Example:\n");
    let first_pascal = to_go_pascal_case(&events[0].name);
    out.push_str(&format!("//   Track.{first_pascal}({first_pascal}Properties{{}})\n"));
    out.push_str("var Track = struct {\n");
    for entry in events {
        let pascal = to_go_pascal_case(&entry.name);
        out.push_str(&format!("\t{pascal} func({pascal}Properties)\n"));
    }
    out.push_str("}{\n");
    for entry in events {
        let pascal = to_go_pascal_case(&entry.name);
        out.push_str(&format!("\t{pascal}: Track{pascal},\n"));
    }
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use infergen_types::{
        CatalogEntry, CatalogEventKind, EventProperty, EventProvenance, EventStatus,
        CATALOG_SCHEMA_VERSION,
    };

    fn make_catalog(entries: Vec<CatalogEntry>) -> Catalog {
        Catalog { schema_version: CATALOG_SCHEMA_VERSION, events: entries }
    }

    fn make_entry(name: &str, status: EventStatus) -> CatalogEntry {
        CatalogEntry {
            id: format!("evt_{name}"),
            name: name.to_owned(),
            description: String::new(),
            status,
            confidence: 0.9,
            kind: CatalogEventKind::ApiCall,
            provenance: vec![EventProvenance {
                source_path: "main.go".into(),
                line: None,
                adapter: String::new(),
            }],
            properties: Vec::new(),
            providers: Vec::new(),
            package: None,
        }
    }

    fn make_prop(name: &str, t: Option<&str>, pii: bool) -> EventProperty {
        EventProperty {
            name: name.into(),
            prop_type: t.map(Into::into),
            required: false,
            pii,
        }
    }

    fn cfg() -> GoCodegenConfig {
        GoCodegenConfig::default()
    }

    // --- package declaration ---

    #[test]
    fn go_generate_empty_catalog_has_package_decl() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("package infergen"), "output:\n{go}");
    }

    #[test]
    fn go_generate_custom_package_name() {
        let config = GoCodegenConfig {
            package_name: "analytics".into(),
            ..Default::default()
        };
        let go = generate_go(&Catalog::default(), &config);
        assert!(go.contains("package analytics"), "output:\n{go}");
    }

    // --- imports ---

    #[test]
    fn go_generate_has_json_import() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("\"encoding/json\""), "output:\n{go}");
    }

    #[test]
    fn go_generate_has_sync_import() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("\"sync\""), "output:\n{go}");
    }

    // --- provider interface ---

    #[test]
    fn go_generate_empty_catalog_has_provider_interface() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("type Provider interface"), "output:\n{go}");
    }

    #[test]
    fn go_generate_has_configure_fn() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("func ConfigureInfergen"), "output:\n{go}");
    }

    // --- consent ---

    #[test]
    fn go_generate_has_set_consent() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("func SetConsent"), "output:\n{go}");
    }

    #[test]
    fn go_generate_has_opt_out() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("func OptOut"), "output:\n{go}");
    }

    #[test]
    fn go_generate_has_opt_in() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("func OptIn"), "output:\n{go}");
    }

    #[test]
    fn go_generate_has_set_region() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("func SetRegion"), "output:\n{go}");
    }

    #[test]
    fn go_generate_has_set_redact_fn() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("func SetRedactFn"), "output:\n{go}");
    }

    // --- dispatch ---

    #[test]
    fn go_generate_has_dispatch() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("func _dispatch"), "output:\n{go}");
    }

    // --- single event ---

    #[test]
    fn go_generate_single_event_struct() {
        let cat = make_catalog(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("UserSignedInProperties"), "output:\n{go}");
    }

    #[test]
    fn go_generate_single_event_track_fn() {
        let cat = make_catalog(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("func TrackUserSignedIn"), "output:\n{go}");
    }

    #[test]
    fn go_generate_single_event_const() {
        let cat = make_catalog(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("EventNameUserSignedIn = \"user_signed_in\""), "output:\n{go}");
    }

    #[test]
    fn go_generate_single_event_track_var() {
        let cat = make_catalog(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("var Track = struct"), "output:\n{go}");
        assert!(go.contains("UserSignedIn"), "output:\n{go}");
    }

    // --- filtering ---

    #[test]
    fn go_generate_ignores_ignored_events() {
        let cat = make_catalog(vec![make_entry("noise", EventStatus::Ignored)]);
        let go = generate_go(&cat, &cfg());
        assert!(!go.contains("noise"), "output:\n{go}");
    }

    #[test]
    fn go_generate_ignores_proposed_by_default() {
        let cat = make_catalog(vec![make_entry("maybe", EventStatus::Proposed)]);
        let go = generate_go(&cat, &cfg());
        assert!(!go.contains("maybe"), "output:\n{go}");
    }

    #[test]
    fn go_generate_includes_proposed_with_flag() {
        let cat = make_catalog(vec![make_entry("maybe", EventStatus::Proposed)]);
        let config = GoCodegenConfig { include_proposed: true, ..Default::default() };
        let go = generate_go(&cat, &config);
        assert!(go.contains("maybe"), "output:\n{go}");
    }

    // --- sorting ---

    #[test]
    fn go_generate_events_sorted_alphabetically() {
        let cat = make_catalog(vec![
            make_entry("z_event", EventStatus::Approved),
            make_entry("a_event", EventStatus::Approved),
        ]);
        let go = generate_go(&cat, &cfg());
        let a_pos = go.find("AEvent").unwrap();
        let z_pos = go.find("ZEvent").unwrap();
        assert!(a_pos < z_pos, "a_event before z_event");
    }

    #[test]
    fn go_generate_properties_sorted_alphabetically() {
        let mut entry = make_entry("api_called", EventStatus::Approved);
        entry.properties.push(make_prop("zebra", Some("string"), false));
        entry.properties.push(make_prop("alpha", Some("string"), false));
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        let alpha_pos = go.find("Alpha").unwrap();
        let zebra_pos = go.find("Zebra").unwrap();
        assert!(alpha_pos < zebra_pos);
    }

    // --- determinism ---

    #[test]
    fn go_generate_deterministic() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let go1 = generate_go(&cat, &cfg());
        let go2 = generate_go(&cat, &cfg());
        assert_eq!(go1, go2);
    }

    // --- property types ---

    #[test]
    fn go_generate_number_type_is_float64() {
        let mut entry = make_entry("api_called", EventStatus::Approved);
        entry.properties.push(make_prop("count", Some("number"), false));
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("Count float64"), "output:\n{go}");
    }

    #[test]
    fn go_generate_boolean_type_is_bool() {
        let mut entry = make_entry("api_called", EventStatus::Approved);
        entry.properties.push(make_prop("cached", Some("boolean"), false));
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("Cached bool"), "output:\n{go}");
    }

    #[test]
    fn go_generate_unknown_type_is_any() {
        let mut entry = make_entry("api_called", EventStatus::Approved);
        entry.properties.push(make_prop("mystery", None, false));
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("Mystery any"), "output:\n{go}");
    }

    #[test]
    fn go_generate_string_type_correct() {
        let mut entry = make_entry("api_called", EventStatus::Approved);
        entry.properties.push(make_prop("method", Some("string"), false));
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("Method string"), "output:\n{go}");
    }

    // --- pii ---

    #[test]
    fn go_generate_pii_property_has_comment() {
        let mut entry = make_entry("user_signed_in", EventStatus::Approved);
        entry.properties.push(make_prop("email", Some("string"), true));
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("pii:\"true\""), "output:\n{go}");
    }

    #[test]
    fn go_generate_non_pii_no_pii_comment() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.properties.push(make_prop("route", Some("string"), false));
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        assert!(!go.contains("pii:\"true\""), "output:\n{go}");
    }

    // --- empty props ---

    #[test]
    fn go_generate_empty_props_uses_map_alias() {
        let cat = make_catalog(vec![make_entry("click_happened", EventStatus::Approved)]);
        let go = generate_go(&cat, &cfg());
        assert!(
            go.contains("ClickHappenedProperties = map[string]any"),
            "output:\n{go}"
        );
    }

    // --- description ---

    #[test]
    fn go_generate_description_in_comment() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.description = "Fires on every page navigation.".into();
        let cat = make_catalog(vec![entry]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("Fires on every page navigation."), "output:\n{go}");
    }

    // --- dispatch in track fn ---

    #[test]
    fn go_generate_track_fn_uses_dispatch() {
        let cat = make_catalog(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        let go = generate_go(&cat, &cfg());
        assert!(go.contains("_dispatch(EventNameUserSignedIn"), "output:\n{go}");
    }

    // --- empty track namespace ---

    #[test]
    fn go_generate_empty_catalog_has_empty_track_namespace() {
        let go = generate_go(&Catalog::default(), &cfg());
        assert!(go.contains("var Track = struct{}{}"), "output:\n{go}");
    }
}
