//! Python SDK code generation from an approved event catalog (E5.1).
//!
//! `generate_python` produces a deterministic, idempotent Python source
//! module: one `TypedDict` + one `track_*` function per approved event,
//! a `_TrackNamespace` class with attribute-style access, and a singleton
//! `track` instance.  A `Provider` Protocol, `configure()`, and `_dispatch()`
//! are included so the generated file is self-contained.

use infergen_types::{CatalogEntry, EventProperty, EventStatus};

use crate::{Catalog, CATALOG_SCHEMA_VERSION};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate a Python SDK source string from an approved catalog.
///
/// Only `Approved` entries are included by default. `Ignored` entries are
/// always excluded. Set `config.include_proposed = true` to also include
/// `Proposed` entries.
///
/// Output is deterministic: events sorted alphabetically, no timestamps.
///
/// # Examples
/// ```rust
/// use infergen_core::codegen::{CodegenConfig, generate_python};
/// use infergen_core::Catalog;
/// let py = generate_python(&Catalog::default(), &CodegenConfig::default());
/// assert!(py.contains("class Provider"));
/// ```
#[must_use]
pub fn generate_python(catalog: &Catalog, config: &super::CodegenConfig) -> String {
    let mut events: Vec<&CatalogEntry> = catalog
        .events
        .iter()
        .filter(|e| {
            e.status == EventStatus::Approved
                || (config.include_proposed && e.status == EventStatus::Proposed)
        })
        .collect();
    events.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    write_header(&mut out);
    write_preamble(&mut out);
    write_event_name_literal(&mut out, &events);

    for entry in &events {
        write_event_section(&mut out, entry);
    }

    write_track_namespace(&mut out, &events);
    out
}

// ---------------------------------------------------------------------------
// Private helpers — name conversion
// ---------------------------------------------------------------------------

/// Convert a snake_case event name to PascalCase.
///
/// `"user_signed_in"` → `"UserSignedIn"`.
fn to_pascal_case(name: &str) -> String {
    crate::namer::split_identifier(name)
        .into_iter()
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

/// Map an `EventProperty.prop_type` value to a Python type string.
///
/// `"string"` → `"str"`, `"number"` → `"float"`, `"boolean"` → `"bool"`.
/// Anything else (including `None`) maps to `"Any"`.
fn py_type(prop_type: Option<&str>) -> &'static str {
    match prop_type {
        Some("string") => "str",
        Some("number") => "float",
        Some("boolean") => "bool",
        _ => "Any",
    }
}

// ---------------------------------------------------------------------------
// Private helpers — output builders
// ---------------------------------------------------------------------------

fn write_header(out: &mut String) {
    out.push_str(
        "# Auto-generated by Infergen. Do not edit — run `infergen generate` to regenerate.\n",
    );
    out.push_str(&format!(
        "# infergen-core v{} · catalog schema v{}\n",
        env!("CARGO_PKG_VERSION"),
        CATALOG_SCHEMA_VERSION,
    ));
    out.push('\n');
}

fn write_preamble(out: &mut String) {
    out.push_str("from __future__ import annotations\n");
    out.push_str("from typing import Any, Protocol, runtime_checkable\n");
    out.push_str("try:\n");
    out.push_str("    from typing import TypedDict\n");
    out.push_str("except ImportError:  # Python < 3.8\n");
    out.push_str("    from typing_extensions import TypedDict  # type: ignore[assignment]\n");
    out.push('\n');

    out.push_str("\n@runtime_checkable\n");
    out.push_str("class Provider(Protocol):\n");
    out.push_str("    \"\"\"A provider that receives analytics events.\"\"\"\n");
    out.push_str("    id: str\n\n");
    out.push_str("    def track(self, event_name: str, properties: dict[str, Any]) -> None:\n");
    out.push_str("        \"\"\"Send a single analytics event.\"\"\"\n");
    out.push_str("        ...\n\n");
    out.push_str("    def flush(self) -> None:\n");
    out.push_str("        \"\"\"Flush buffered events (optional).\"\"\"\n");
    out.push_str("        ...\n\n");
    out.push_str("    def shutdown(self) -> None:\n");
    out.push_str("        \"\"\"Shut down the provider (optional).\"\"\"\n");
    out.push_str("        ...\n\n");

    out.push_str("\n_providers: list[Provider] = []\n\n");

    out.push_str("def configure(providers: list[Provider]) -> None:\n");
    out.push_str("    \"\"\"Configure the Infergen runtime. Call once before any track calls.\"\"\"\n");
    out.push_str("    global _providers\n");
    out.push_str("    _providers = list(providers)\n\n");

    out.push_str("def _dispatch(event_name: str, properties: dict[str, Any]) -> None:\n");
    out.push_str("    for provider in _providers:\n");
    out.push_str("        provider.track(event_name, properties)\n\n");
}

fn write_event_name_literal(out: &mut String, events: &[&CatalogEntry]) {
    out.push('\n');
    if events.is_empty() {
        out.push_str("# No approved events in catalog.\n");
        out.push_str("EventName = None\n\n");
    } else {
        out.push_str("from typing import Literal\n\n");
        out.push_str("EventName = Literal[\n");
        for entry in events {
            out.push_str(&format!("    \"{}\",\n", entry.name));
        }
        out.push_str("]\n\n");
    }
}

fn write_section_divider(out: &mut String, name: &str) {
    let prefix = format!("# ─── {} ", name);
    let bar_len = 80usize.saturating_sub(prefix.len());
    let bar = "─".repeat(bar_len.max(2));
    out.push('\n');
    out.push_str(&format!("{}{}\n\n", prefix, bar));
}

fn write_typed_dict(out: &mut String, entry: &CatalogEntry) {
    let pascal = to_pascal_case(&entry.name);
    let mut sorted_props: Vec<&EventProperty> = entry.properties.iter().collect();
    sorted_props.sort_by(|a, b| a.name.cmp(&b.name));

    if sorted_props.is_empty() {
        out.push_str(&format!(
            "{pascal}Properties = dict[str, Any]  # no declared properties\n"
        ));
    } else {
        out.push_str(&format!("class {pascal}Properties(TypedDict, total=False):\n"));
        for prop in &sorted_props {
            let t = py_type(prop.prop_type.as_deref());
            if prop.pii {
                out.push_str(&format!(
                    "    {}  # type: {}  # PII: handle with care\n",
                    prop.name, t
                ));
                // Also emit the actual typed field for mypy.
                out.push_str(&format!("    {}: {}\n", prop.name, t));
            } else {
                out.push_str(&format!("    {}: {}\n", prop.name, t));
            }
        }
        out.push('\n');
    }
}

fn write_track_function(out: &mut String, entry: &CatalogEntry) {
    let pascal = to_pascal_case(&entry.name);
    out.push('\n');
    if entry.description.is_empty() {
        out.push_str(&format!(
            "def track_{name}(properties: {pascal}Properties) -> None:\n",
            name = entry.name
        ));
        out.push_str(&format!(
            "    \"\"\"Track a {} event.\"\"\"\n",
            entry.name
        ));
    } else {
        out.push_str(&format!(
            "def track_{name}(properties: {pascal}Properties) -> None:\n",
            name = entry.name
        ));
        out.push_str("    \"\"\"\n");
        out.push_str(&format!("    Track a {} event.\n", entry.name));
        out.push('\n');
        out.push_str(&format!("    {}\n", entry.description));
        out.push_str("    \"\"\"\n");
    }
    out.push_str(&format!(
        "    _dispatch(\"{}\", dict(properties))\n\n",
        entry.name
    ));
}

fn write_event_section(out: &mut String, entry: &CatalogEntry) {
    write_section_divider(out, &entry.name);
    write_typed_dict(out, entry);
    write_track_function(out, entry);
}

fn write_track_namespace(out: &mut String, events: &[&CatalogEntry]) {
    out.push('\n');
    write_section_divider(out, "track namespace");

    out.push_str("class _TrackNamespace:\n");
    out.push_str("    \"\"\"Track any event by name with fully typed properties.\"\"\"\n");
    out.push('\n');

    if events.is_empty() {
        out.push_str("    pass\n\n");
    } else {
        for entry in events {
            let pascal = to_pascal_case(&entry.name);
            out.push_str(&format!(
                "    def {name}(self, properties: {pascal}Properties) -> None:\n",
                name = entry.name
            ));
            out.push_str(&format!(
                "        track_{name}(properties)\n\n",
                name = entry.name
            ));
        }
    }

    out.push_str("track = _TrackNamespace()\n");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use infergen_types::{
        CatalogEntry, CatalogEventKind, EventProperty, EventProvenance, EventStatus,
        CATALOG_SCHEMA_VERSION,
    };

    use crate::codegen::CodegenConfig;

    fn make_catalog(entries: Vec<CatalogEntry>) -> Catalog {
        Catalog { schema_version: CATALOG_SCHEMA_VERSION, events: entries, flows: Vec::new() }
    }

    fn make_entry(name: &str, status: EventStatus) -> CatalogEntry {
        CatalogEntry {
            id: format!("evt_{name}"),
            name: name.to_owned(),
            description: String::new(),
            status,
            confidence: 0.9,
            kind: CatalogEventKind::PageView,
            provenance: vec![EventProvenance {
                source_path: "views.py".into(),
                line: None,
                adapter: String::new(),
            }],
            properties: Vec::new(),
            providers: Vec::new(),
            package: None,
            flow_ids: Vec::new(),
        }
    }

    fn make_prop(name: &str, t: Option<&str>, pii: bool) -> EventProperty {
        EventProperty {
            name: name.into(),
            prop_type: t.map(Into::into),
            required: false,
            pii,
        }
    }

    // --- name helpers --------------------------------------------------------

    #[test]
    fn to_pascal_single_word() {
        assert_eq!(to_pascal_case("submit"), "Submit");
    }

    #[test]
    fn to_pascal_snake_case() {
        assert_eq!(to_pascal_case("user_signed_in"), "UserSignedIn");
    }

    // --- py_type -------------------------------------------------------------

    #[test]
    fn py_type_string_to_str() {
        assert_eq!(py_type(Some("string")), "str");
    }

    #[test]
    fn py_type_number_to_float() {
        assert_eq!(py_type(Some("number")), "float");
    }

    #[test]
    fn py_type_boolean_to_bool() {
        assert_eq!(py_type(Some("boolean")), "bool");
    }

    #[test]
    fn py_type_none_to_any() {
        assert_eq!(py_type(None), "Any");
    }

    #[test]
    fn py_type_unknown_to_any() {
        assert_eq!(py_type(Some("custom")), "Any");
    }

    // --- generate_python -----------------------------------------------------

    #[test]
    fn empty_catalog_has_event_name_none() {
        let py = generate_python(&Catalog::default(), &CodegenConfig::default());
        assert!(py.contains("EventName = None"), "output:\n{py}");
    }

    #[test]
    fn empty_catalog_has_provider_protocol() {
        let py = generate_python(&Catalog::default(), &CodegenConfig::default());
        assert!(py.contains("class Provider"), "output:\n{py}");
    }

    #[test]
    fn empty_catalog_has_configure() {
        let py = generate_python(&Catalog::default(), &CodegenConfig::default());
        assert!(py.contains("def configure("), "output:\n{py}");
    }

    #[test]
    fn empty_catalog_has_dispatch() {
        let py = generate_python(&Catalog::default(), &CodegenConfig::default());
        assert!(py.contains("def _dispatch("), "output:\n{py}");
    }

    #[test]
    fn single_event_typed_dict_present() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(py.contains("PageViewedProperties"), "output:\n{py}");
    }

    #[test]
    fn single_event_track_function_present() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(py.contains("def track_page_viewed("), "output:\n{py}");
    }

    #[test]
    fn single_event_namespace_method_present() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(py.contains("def page_viewed("), "output:\n{py}");
    }

    #[test]
    fn track_singleton_present() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(py.contains("track = _TrackNamespace()"), "output:\n{py}");
    }

    #[test]
    fn pii_prop_has_comment() {
        let mut entry = make_entry("user_signed_in", EventStatus::Approved);
        entry.properties.push(make_prop("email", Some("string"), true));
        let py = generate_python(&make_catalog(vec![entry]), &CodegenConfig::default());
        assert!(py.contains("PII: handle with care"), "output:\n{py}");
    }

    #[test]
    fn string_type_maps_to_str() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.properties.push(make_prop("route", Some("string"), false));
        let py = generate_python(&make_catalog(vec![entry]), &CodegenConfig::default());
        assert!(py.contains("route: str"), "output:\n{py}");
    }

    #[test]
    fn number_type_maps_to_float() {
        let mut entry = make_entry("counted", EventStatus::Approved);
        entry.properties.push(make_prop("count", Some("number"), false));
        let py = generate_python(&make_catalog(vec![entry]), &CodegenConfig::default());
        assert!(py.contains("count: float"), "output:\n{py}");
    }

    #[test]
    fn boolean_type_maps_to_bool() {
        let mut entry = make_entry("toggled", EventStatus::Approved);
        entry.properties.push(make_prop("is_active", Some("boolean"), false));
        let py = generate_python(&make_catalog(vec![entry]), &CodegenConfig::default());
        assert!(py.contains("is_active: bool"), "output:\n{py}");
    }

    #[test]
    fn none_type_maps_to_any() {
        let mut entry = make_entry("misc", EventStatus::Approved);
        entry.properties.push(make_prop("data", None, false));
        let py = generate_python(&make_catalog(vec![entry]), &CodegenConfig::default());
        assert!(py.contains("data: Any"), "output:\n{py}");
    }

    #[test]
    fn sorted_alphabetically() {
        let cat = make_catalog(vec![
            make_entry("z_event", EventStatus::Approved),
            make_entry("a_event", EventStatus::Approved),
        ]);
        let py = generate_python(&cat, &CodegenConfig::default());
        let a_pos = py.find("a_event").unwrap();
        let z_pos = py.find("z_event").unwrap();
        assert!(a_pos < z_pos, "a_event should appear before z_event");
    }

    #[test]
    fn ignores_ignored_events() {
        let cat = make_catalog(vec![make_entry("noise", EventStatus::Ignored)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(!py.contains("noise"), "output:\n{py}");
    }

    #[test]
    fn ignores_proposed_by_default() {
        let cat = make_catalog(vec![make_entry("maybe", EventStatus::Proposed)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(!py.contains("def track_maybe"), "output:\n{py}");
    }

    #[test]
    fn includes_proposed_with_flag() {
        let cat = make_catalog(vec![make_entry("maybe", EventStatus::Proposed)]);
        let config = CodegenConfig { include_proposed: true };
        let py = generate_python(&cat, &config);
        assert!(py.contains("def track_maybe"), "output:\n{py}");
    }

    #[test]
    fn deterministic() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let config = CodegenConfig::default();
        let py1 = generate_python(&cat, &config);
        let py2 = generate_python(&cat, &config);
        assert_eq!(py1, py2);
    }

    #[test]
    fn empty_props_uses_dict_any() {
        let cat = make_catalog(vec![make_entry("click_happened", EventStatus::Approved)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(
            py.contains("ClickHappenedProperties = dict[str, Any]"),
            "empty props should use dict[str, Any]\noutput:\n{py}"
        );
    }

    #[test]
    fn event_name_literal_lists_all() {
        let cat = make_catalog(vec![
            make_entry("page_viewed", EventStatus::Approved),
            make_entry("user_signed_in", EventStatus::Approved),
        ]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(py.contains("\"page_viewed\""), "output:\n{py}");
        assert!(py.contains("\"user_signed_in\""), "output:\n{py}");
    }

    #[test]
    fn dispatch_called_in_track_fn() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let py = generate_python(&cat, &CodegenConfig::default());
        assert!(
            py.contains("_dispatch(\"page_viewed\""),
            "track fn must call _dispatch\noutput:\n{py}"
        );
    }
}
