//! Ruby code generation from an approved event catalog.
//!
//! `generate_ruby` produces a deterministic, idempotent Ruby source file:
//! - A `module Infergen` (or custom name) wrapping the entire SDK.
//! - Consent constants and runtime state.
//! - `configure`, `set_consent`, `opt_in`, `opt_out`, `set_region`,
//!   `set_redact_fn`, `_dispatch` module methods.
//! - Per-event: an event-name constant, an optional `Struct` for typed
//!   properties, and a `def self.track_*` method.
//! - A `Track` sub-module with `module_function` delegates for ergonomic use.

use infergen_types::{CatalogEntry, EventProperty, EventStatus};

use crate::{Catalog, CATALOG_SCHEMA_VERSION};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Configuration for Ruby code generation.
#[derive(Debug, Clone)]
pub struct RubyCodegenConfig {
    /// Also generate code for `Proposed` events in addition to `Approved`.
    ///
    /// Default: `false`.
    pub include_proposed: bool,
    /// Ruby module name wrapping the SDK. Default: `"Infergen"`.
    pub module_name: String,
}

impl Default for RubyCodegenConfig {
    fn default() -> Self {
        Self {
            include_proposed: false,
            module_name: "Infergen".to_owned(),
        }
    }
}

/// Generate a Ruby SDK source string from an approved catalog.
///
/// Only `Approved` entries are included by default. `Ignored` entries are
/// always excluded. Set `config.include_proposed = true` to also include
/// `Proposed` entries.
///
/// Output is deterministic: events sorted alphabetically, no timestamps.
#[must_use]
pub fn generate_ruby(catalog: &Catalog, config: &RubyCodegenConfig) -> String {
    let mut events: Vec<&CatalogEntry> = catalog
        .events
        .iter()
        .filter(|e| {
            e.status == EventStatus::Approved
                || (config.include_proposed && e.status == EventStatus::Proposed)
        })
        .collect();
    events.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    let m = &config.module_name;

    write_header(&mut out);
    out.push_str(&format!("module {m}\n"));
    write_consent_constants(&mut out);
    write_runtime_state(&mut out);
    write_class_self_block(&mut out);

    // Event-name constants
    if !events.is_empty() {
        out.push('\n');
        out.push_str("  # Event name constants.\n");
        for entry in &events {
            let const_name = to_const_name(&entry.name);
            out.push_str(&format!(
                "  {const_name} = \"{}\".freeze\n",
                entry.name
            ));
        }
    }

    // Per-event sections
    for entry in &events {
        write_event_section(&mut out, entry, m);
    }

    // Track sub-module
    write_track_module(&mut out, &events, m);

    out.push_str("end\n");
    out
}

// ---------------------------------------------------------------------------
// Name conversion helpers
// ---------------------------------------------------------------------------

/// `"user_signed_in"` → `"USER_SIGNED_IN"`
fn to_const_name(name: &str) -> String {
    name.to_ascii_uppercase()
}

/// `"user_signed_in"` → `"UserSignedIn"`
fn to_pascal_case(name: &str) -> String {
    crate::namer::split_identifier(name)
        .into_iter()
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

/// `"user_signed_in"` → `"user_signed_in"` (already snake_case; kept as-is)
fn to_method_name(name: &str) -> &str {
    name
}

/// Map a catalog property type to a Ruby type annotation comment.
fn ruby_type(prop_type: Option<&str>) -> &'static str {
    match prop_type {
        Some("string") => "String",
        Some("number") => "Float",
        Some("boolean") => "TrueClass, FalseClass",
        _ => "Object",
    }
}

// ---------------------------------------------------------------------------
// Output builders
// ---------------------------------------------------------------------------

fn write_header(out: &mut String) {
    out.push_str("# Auto-generated by Infergen. Do not edit — run `infergen generate` to regenerate.\n");
    out.push_str(&format!(
        "# infergen-core v{} · catalog schema v{}\n",
        env!("CARGO_PKG_VERSION"),
        CATALOG_SCHEMA_VERSION,
    ));
    out.push_str("# frozen_string_literal: true\n");
    out.push('\n');
}

fn write_consent_constants(out: &mut String) {
    out.push('\n');
    out.push_str("  # Consent state constants.\n");
    out.push_str("  CONSENT_UNKNOWN = :unknown\n");
    out.push_str("  CONSENT_GRANTED = :granted\n");
    out.push_str("  CONSENT_DENIED  = :denied\n");
}

fn write_runtime_state(out: &mut String) {
    out.push('\n');
    out.push_str("  @_providers = []\n");
    out.push_str("  @_consent   = CONSENT_UNKNOWN\n");
    out.push_str("  @_region    = nil\n");
    out.push_str("  @_redact_fn = nil\n");
    out.push_str("  @_mutex     = Mutex.new\n");
}

fn write_class_self_block(out: &mut String) {
    out.push('\n');
    out.push_str("  class << self\n");

    // configure
    out.push_str("    # Configure the Infergen runtime. Call once before any track calls.\n");
    out.push_str("    def configure(providers: [], consent: CONSENT_UNKNOWN, region: nil)\n");
    out.push_str("      @_mutex.synchronize do\n");
    out.push_str("        @_providers = providers\n");
    out.push_str("        @_consent   = consent\n");
    out.push_str("        @_region    = region\n");
    out.push_str("      end\n");
    out.push_str("    end\n");
    out.push('\n');

    // set_consent
    out.push_str("    def set_consent(state)\n");
    out.push_str("      @_mutex.synchronize { @_consent = state }\n");
    out.push_str("    end\n");
    out.push('\n');

    // opt_in / opt_out
    out.push_str("    def opt_in\n");
    out.push_str("      set_consent(CONSENT_GRANTED)\n");
    out.push_str("    end\n");
    out.push('\n');
    out.push_str("    def opt_out\n");
    out.push_str("      set_consent(CONSENT_DENIED)\n");
    out.push_str("    end\n");
    out.push('\n');

    // set_region
    out.push_str("    def set_region(region)\n");
    out.push_str("      @_mutex.synchronize { @_region = region }\n");
    out.push_str("    end\n");
    out.push('\n');

    // set_redact_fn
    out.push_str("    def set_redact_fn(&block)\n");
    out.push_str("      @_mutex.synchronize { @_redact_fn = block }\n");
    out.push_str("    end\n");
    out.push('\n');

    // _dispatch
    out.push_str("    # @api private\n");
    out.push_str("    def _dispatch(event_name, props)\n");
    out.push_str("      consent, redact, providers = @_mutex.synchronize do\n");
    out.push_str("        [@_consent, @_redact_fn, @_providers.dup]\n");
    out.push_str("      end\n");
    out.push_str("      return if consent == CONSENT_DENIED\n");
    out.push_str("      if redact\n");
    out.push_str("        props = props.each_with_object({}) { |(k, v), h| h[k] = redact.call(event_name.to_s, k.to_s, v) }\n");
    out.push_str("      end\n");
    out.push_str("      providers.each { |provider| provider.track(event_name, props) }\n");
    out.push_str("    end\n");

    out.push_str("  end\n");
}

fn write_section_divider(out: &mut String, name: &str) {
    let prefix = format!("  # ─── {} ", name);
    let bar_len = 80usize.saturating_sub(prefix.len());
    let bar = "─".repeat(bar_len.max(2));
    out.push('\n');
    out.push_str(&format!("{}{}\n", prefix, bar));
    out.push('\n');
}

fn write_event_section(out: &mut String, entry: &CatalogEntry, _module_name: &str) {
    write_section_divider(out, &entry.name);

    let pascal = to_pascal_case(&entry.name);
    let method = to_method_name(&entry.name);
    let const_name = to_const_name(&entry.name);

    let mut sorted_props: Vec<&EventProperty> = entry.properties.iter().collect();
    sorted_props.sort_by(|a, b| a.name.cmp(&b.name));

    // Struct definition (only when properties present)
    if !sorted_props.is_empty() {
        let description = if entry.description.is_empty() {
            format!("Properties for the {} event.", entry.name)
        } else {
            entry.description.clone()
        };
        out.push_str(&format!("  # {}\n", description));
        let fields: Vec<String> = sorted_props.iter().map(|p| format!(":{}", p.name)).collect();
        out.push_str(&format!(
            "  {}Properties = Struct.new({}, keyword_init: true)\n",
            pascal,
            fields.join(", ")
        ));
        // PII and type annotations
        for prop in &sorted_props {
            let t = ruby_type(prop.prop_type.as_deref());
            if prop.pii {
                out.push_str(&format!(
                    "  # @attr {} [{}] # pii: true\n",
                    prop.name, t
                ));
            } else {
                out.push_str(&format!("  # @attr {} [{}]\n", prop.name, t));
            }
        }
        out.push('\n');
    }

    // Track function
    if entry.description.is_empty() {
        out.push_str(&format!("  # Track the {} event.\n", entry.name));
    } else {
        out.push_str(&format!("  # Track the {} event.\n", entry.name));
        out.push_str(&format!("  # {}\n", entry.description));
    }

    if !sorted_props.is_empty() {
        out.push_str(&format!(
            "  # @param props [{}Properties, Hash]\n",
            pascal
        ));
        out.push_str(&format!("  def self.track_{}(props = {{}})\n", method));
        out.push_str(&format!(
            "    _dispatch({const_name}, props.is_a?({}Properties) ? props.to_h : props)\n",
            pascal,
        ));
        out.push_str("  end\n");
    } else {
        out.push_str(&format!("  # @param props [Hash]\n"));
        out.push_str(&format!("  def self.track_{}(props = {{}})\n", method));
        out.push_str(&format!("    _dispatch({const_name}, props)\n"));
        out.push_str("  end\n");
    }
}

fn write_track_module(out: &mut String, events: &[&CatalogEntry], module_name: &str) {
    out.push('\n');
    out.push_str(&format!(
        "  # Namespace for all tracked events.\n"
    ));
    if !events.is_empty() {
        let first = to_method_name(&events[0].name);
        out.push_str(&format!("  # @example\n"));
        out.push_str(&format!(
            "  #   {}::Track.{}({{...}})\n",
            module_name, first
        ));
    }
    out.push_str("  module Track\n");
    out.push_str("    module_function\n");
    out.push('\n');
    for entry in events {
        let method = to_method_name(&entry.name);
        out.push_str(&format!("    # @param props [Hash]\n"));
        out.push_str(&format!("    def {}(props = {{}})\n", method));
        out.push_str(&format!("      {}.track_{}(props)\n", module_name, method));
        out.push_str("    end\n");
        out.push('\n');
    }
    out.push_str("  end\n");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use infergen_types::{
        CatalogEntry, CatalogEventKind, EventProperty, EventProvenance, EventStatus,
        CATALOG_SCHEMA_VERSION,
    };

    fn make_catalog(entries: Vec<CatalogEntry>) -> Catalog {
        Catalog { schema_version: CATALOG_SCHEMA_VERSION, events: entries, flows: Vec::new() }
    }

    fn make_entry(name: &str, status: EventStatus) -> CatalogEntry {
        CatalogEntry {
            id: format!("evt_{name}"),
            name: name.to_owned(),
            description: String::new(),
            status,
            confidence: 0.9,
            kind: CatalogEventKind::PageView,
            provenance: vec![EventProvenance {
                source_path: "app/controllers/users_controller.rb".into(),
                line: None,
                adapter: "rails".into(),
            }],
            properties: Vec::new(),
            providers: Vec::new(),
            package: None,
            flow_ids: Vec::new(),
        }
    }

    fn make_prop(name: &str, t: Option<&str>, pii: bool) -> EventProperty {
        EventProperty { name: name.into(), prop_type: t.map(Into::into), required: false, pii }
    }

    fn mk_gen(entries: Vec<CatalogEntry>) -> String {
        generate_ruby(&make_catalog(entries), &RubyCodegenConfig::default())
    }

    fn mk_gen_with(entries: Vec<CatalogEntry>, config: RubyCodegenConfig) -> String {
        generate_ruby(&make_catalog(entries), &config)
    }

    #[test]
    fn ruby_generate_empty_catalog_has_module_decl() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("module Infergen"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_custom_module_name() {
        let config = RubyCodegenConfig {
            module_name: "Analytics".to_owned(),
            ..Default::default()
        };
        let rb = mk_gen_with(vec![], config);
        assert!(rb.contains("module Analytics"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_frozen_literal() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("frozen_string_literal: true"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_consent_constants() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("CONSENT_UNKNOWN"), "output:\n{rb}");
        assert!(rb.contains("CONSENT_GRANTED"), "output:\n{rb}");
        assert!(rb.contains("CONSENT_DENIED"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_configure_fn() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("def configure"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_set_consent() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("def set_consent"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_opt_in() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("def opt_in"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_opt_out() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("def opt_out"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_set_region() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("def set_region"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_set_redact_fn() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("def set_redact_fn"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_has_dispatch() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("def _dispatch"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_single_event_struct() {
        let mut entry = make_entry("user_signed_in", EventStatus::Approved);
        entry.properties.push(make_prop("auth_method", Some("string"), false));
        let rb = mk_gen(vec![entry]);
        assert!(rb.contains("UserSignedInProperties = Struct.new"), "output:\n{rb}");
        assert!(rb.contains(":auth_method"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_single_event_track_fn() {
        let rb = mk_gen(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        assert!(rb.contains("def self.track_user_signed_in"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_single_event_constant() {
        let rb = mk_gen(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        assert!(rb.contains("USER_SIGNED_IN = \"user_signed_in\""), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_single_event_track_module() {
        let rb = mk_gen(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        assert!(rb.contains("module Track"), "output:\n{rb}");
        assert!(rb.contains("def user_signed_in"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_ignores_ignored_events() {
        let rb = mk_gen(vec![make_entry("noise_event", EventStatus::Ignored)]);
        assert!(!rb.contains("noise_event"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_ignores_proposed_by_default() {
        let rb = mk_gen(vec![make_entry("maybe_event", EventStatus::Proposed)]);
        assert!(!rb.contains("maybe_event"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_includes_proposed_with_flag() {
        let config = RubyCodegenConfig { include_proposed: true, ..Default::default() };
        let rb = mk_gen_with(vec![make_entry("maybe_event", EventStatus::Proposed)], config);
        assert!(rb.contains("maybe_event"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_events_sorted_alphabetically() {
        let rb = mk_gen(vec![
            make_entry("z_event", EventStatus::Approved),
            make_entry("a_event", EventStatus::Approved),
        ]);
        let a_pos = rb.find("a_event").unwrap();
        let z_pos = rb.find("z_event").unwrap();
        assert!(a_pos < z_pos, "a_event should appear before z_event");
    }

    #[test]
    fn ruby_generate_properties_sorted_alphabetically() {
        let mut entry = make_entry("api_called", EventStatus::Approved);
        entry.properties.push(make_prop("zebra", Some("string"), false));
        entry.properties.push(make_prop("alpha", Some("string"), false));
        let rb = mk_gen(vec![entry]);
        let alpha_pos = rb.find(":alpha").unwrap();
        let zebra_pos = rb.find(":zebra").unwrap();
        assert!(alpha_pos < zebra_pos);
    }

    #[test]
    fn ruby_generate_deterministic() {
        let cat = make_catalog(vec![make_entry("page_viewed", EventStatus::Approved)]);
        let config = RubyCodegenConfig::default();
        let rb1 = generate_ruby(&cat, &config);
        let rb2 = generate_ruby(&cat, &config);
        assert_eq!(rb1, rb2);
    }

    #[test]
    fn ruby_generate_empty_props_no_struct() {
        let rb = mk_gen(vec![make_entry("click_happened", EventStatus::Approved)]);
        assert!(!rb.contains("ClickHappenedProperties"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_pii_property_has_comment() {
        let mut entry = make_entry("user_signed_in", EventStatus::Approved);
        entry.properties.push(make_prop("email", Some("string"), true));
        let rb = mk_gen(vec![entry]);
        assert!(rb.contains("pii: true"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_description_in_comment() {
        let mut entry = make_entry("page_viewed", EventStatus::Approved);
        entry.description = "Fires on every page navigation.".into();
        let rb = mk_gen(vec![entry]);
        assert!(rb.contains("Fires on every page navigation."), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_string_type_in_comment() {
        let mut entry = make_entry("user_signed_in", EventStatus::Approved);
        entry.properties.push(make_prop("auth_method", Some("string"), false));
        let rb = mk_gen(vec![entry]);
        assert!(rb.contains("String"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_number_type_in_comment() {
        let mut entry = make_entry("item_purchased", EventStatus::Approved);
        entry.properties.push(make_prop("price", Some("number"), false));
        let rb = mk_gen(vec![entry]);
        assert!(rb.contains("Float"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_dispatch_in_track_fn() {
        let rb = mk_gen(vec![make_entry("user_signed_in", EventStatus::Approved)]);
        assert!(rb.contains("_dispatch(USER_SIGNED_IN"), "output:\n{rb}");
    }

    #[test]
    fn ruby_generate_empty_track_module_for_empty_catalog() {
        let rb = mk_gen(vec![]);
        assert!(rb.contains("module Track"), "output:\n{rb}");
        assert!(rb.contains("module_function"), "output:\n{rb}");
    }
}
